import { describe, expect, it } from 'vitest'
import { readWorkflow } from './helpers.js'

describe('GitHub Actions activation workflow', () => {
  it('uses the exact label trigger, issue concurrency, pinned runtime, minimal explicit scopes, and split credentials', async () => {
    const workflow = await readWorkflow()
    expect(workflow).toContain('issues:')
    expect(workflow).toContain('types: [labeled]')
    expect(workflow).toContain("github.event.label.name == 'agent-ready'")
    expect(workflow).toContain('issue-${{ github.event.issue.number }}')
    expect(workflow).toContain('cancel-in-progress: false')
    expect(workflow).toContain('actions: read')
    expect(workflow).toContain('contents: write')
    expect(workflow).toContain('issues: write')
    expect(workflow).toContain('pull-requests: write')
    expect(workflow).toContain('persist-credentials: false')
    expect(workflow).toContain('node-version: 22.23.1')
    expect(workflow).toContain('10.9.8')
    expect(workflow).toContain('vars.OMA_MAINTAINER_BOT_PR_CREATION_ENABLED')
    expect(workflow).toContain('--pr-creation-attested "$OMA_PR_CREATION_ATTESTED"')
    expect(workflow).not.toContain('--claim-id "${{')
    expect(workflow).not.toContain("const baseSha = '${{")
    expect(workflow).toContain('actions/checkout@11d5960a326750d5838078e36cf38b85af677262')
    expect(workflow).toContain('actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020')
    expect(workflow).toContain('actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b')
    expect(workflow).not.toMatch(/uses:\s+actions\/(?:checkout|setup-node|github-script)@v\d/)
    expect(workflow).not.toContain('pull_request_target')
    expect(workflow).toContain("const terminalClaim = sameClaim && !runningClaim")
    expect(workflow).toContain("terminalClaim ? previous.status : 'FAILED'")
    const engine = workflow.slice(workflow.indexOf('- name: Run OMA'), workflow.indexOf('- name: Revalidate'))
    expect(engine).toContain('DEEPSEEK_API_KEY')
    expect(engine).not.toContain('MAINTAINER_BOT_GITHUB_TOKEN')
    const finalize = workflow.slice(workflow.indexOf('- name: Revalidate'), workflow.indexOf('- name: Publish infrastructure'))
    expect(finalize).toContain('MAINTAINER_BOT_GITHUB_TOKEN')
    expect(finalize).not.toContain('DEEPSEEK_API_KEY')
  })
})
